set cpu 11/44
set cpu 2M
set clock nocatchup

attach rl0 storage-server.dsk
set hk enable
attach hk0 data.dsk

set xq disable
set xu enable
set xu type=deuna
set xu mac=%SIM_XU_MAC%
attach xu vde:/vde/dsm_switch

expect "Please enter today's date  <1-Jan-80>" send "1-Jan-80\r"; go
expect "Is today Tuesday ? <Y>" send "\r"; go
expect "Please enter time  [ HH:MM:SS  ]  >" send "%TIME_HH%:%TIME_MM%:%TIME_SS%\r"; go
expect "Is this" send "Y\r"; go
expect "Are you sure you entered time on 24-hour clock ? <Y>" send "\r"; go
; Saved-startup-file boot prompt
expect "Start up the default system" send "Y\r"; go
; Fallback: first-boot
expect "baseline mode" send "N\r"; go
expect "Configuration ?" send "1\r"; go
expect "Apply patches to memory" send "N\r"; go
expect "Start up the Journal" send "N\r"; go
expect "Startup Distributed Database Processing" send "Y\r"; go
expect "Enter the number of DDP servers" send "\r"; go
expect "Start the Caretaker" send "Y\r"; go
expect "Enter the Printer Number" send "\r"; go
expect "Automatic logging of DSM errors" send "N\r"; go
expect "Mount additional disk volumes" send "Y\r"; go
expect "Mount a volume on which disk unit" send "DM0\r"; go
expect "Mount DM0 for access via" send "D\r"; go
expect "What name do you wish to use for this volume set" send "\r"; go
expect "Mount additional disk volumes" send "N\r"; go
expect "Make this the new startup file" send "Y\r"; go
expect "Make 1 the new default" send "Y\r"; go

set on
on SIGTERM goto handle_stop
on SIGINT goto handle_stop

boot rl0

:handle_stop
echo Shutting down PDP11 simulator
exit
