set cpu 11/44
set cpu 2M
set clock nocatchup
set cpu idle

attach rl0 terminal-server.dsk

set xq disable
set xu enable
set xu type=deuna
set xu mac=%SIM_XU_MAC%
attach xu vde:/vde/dsm_switch

set dz disable
set vh enable
set vh lines=64
set vh0 dhu
set vh1 dhu
set vh2 dhu
set vh3 dhu
set vh0 fastdma
set vh1 fastdma
set vh2 fastdma
set vh3 fastdma
set vh address=17760440
set vh vector=300
set vh0 modem
set vh1 modem
set vh2 modem
set vh3 modem
set vh0 hangup
set vh1 hangup
set vh2 hangup
set vh3 hangup
attach vh 1337,SPEED=*32;nomessage

expect "Please enter today's date  <1-Jan-80>" send "1-Jan-80\r"; go
expect "Is today Tuesday ? <Y>" send "\r"; go
expect "Please enter time  [ HH:MM:SS  ]  >" send "%TIME_HH%:%TIME_MM%:%TIME_SS%\r"; go
expect "Is this" send "Y\r"; go
expect "Are you sure you entered time on 24-hour clock ? <Y>" send "\r"; go
; Saved-startup-file boot prompt
expect "Start up the default system" send "Y\r"; go
; Fallback: first-boot
expect "Do you wish to remain in baseline mode" send "N\r"; go
expect "Configuration ?" send "\r"; go
expect "Apply patches to memory" send "N\r"; go
expect "Start up the Journal" send "N\r"; go
expect "Startup Distributed Database Processing" send "Y\r"; go
expect "Enter the number of DDP servers" send "\r"; go
expect "Start the Caretaker" send "Y\r"; go
expect "Enter the Printer Number" send "\r"; go
expect "Automatic logging of DSM errors" send "N\r"; go
expect "Mount additional disk volumes" send "N\r"; go
expect "Make this the new startup file" send "Y\r"; go
expect "Make 1 the new default" send "Y\r"; go

set on
on SIGTERM goto handle_stop
on SIGINT goto handle_stop

boot rl0

:handle_stop
echo Shutting down PDP11 simulator
detach vh
exit
