name: flagdrive

services:
  flagdrive-service:
    restart: unless-stopped
    cpus: 2
    mem_limit: 4G
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4859:4859"
    depends_on:
      - flagdrive-db
    volumes:
      - database:/ctf/data
    environment:
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgres://flagdrive:flagdrivepassword@flagdrive-db:5432/flagdrive

  flagdrive-db:
    image: postgres@sha256:e013e867e712fec275706a6c51c966f0bb0c93cfa8f51000f85a15f9865a28cb
    restart: unless-stopped
    environment:
      POSTGRES_USER: flagdrive
      POSTGRES_PASSWORD: flagdrivepassword
      POSTGRES_DB: flagdrive
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  database:
  postgres-data: