FROM golang:1.21-alpine AS builder

WORKDIR /build
COPY livetrack/go.mod livetrack/go.sum ./
RUN go mod download

COPY livetrack/main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -o livetrack main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /build/livetrack .
CMD ["./livetrack"]
