#!/bin/sh
set -eu

mkdir -p /data/pdfs /data/exports /data/packets

cat > /app/cleanup.env <<EOF
SIGNMEMAYBE_DB_PATH=${SIGNMEMAYBE_DB_PATH:-/data/signmemaybe.sqlite3}
SIGNMEMAYBE_PDF_ROOT=${SIGNMEMAYBE_PDF_ROOT:-/data/pdfs}
SIGNMEMAYBE_EXPORT_ROOT=${SIGNMEMAYBE_EXPORT_ROOT:-/data/exports}
SIGNMEMAYBE_PACKET_ROOT=${SIGNMEMAYBE_PACKET_ROOT:-/data/packets}
SIGNMEMAYBE_MAX_UPLOAD_BYTES=${SIGNMEMAYBE_MAX_UPLOAD_BYTES:-10485760}
SIGNMEMAYBE_CLEANUP_RETENTION_SECONDS=${SIGNMEMAYBE_CLEANUP_RETENTION_SECONDS:-720}
SIGNMEMAYBE_CLEANUP_SWEEP_FILES=${SIGNMEMAYBE_CLEANUP_SWEEP_FILES:-false}
SIGNMEMAYBE_PCAP_ROOT=${SIGNMEMAYBE_PCAP_ROOT:-/pcaps}
SIGNMEMAYBE_PCAP_RETENTION_MINUTES=${SIGNMEMAYBE_PCAP_RETENTION_MINUTES:-30}
EOF

exec cron -f -L 8
