// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: compress/compress.proto

package compresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressRequest) Reset() {
	*x = CompressRequest{}
	mi := &file_compress_compress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressRequest) ProtoMessage() {}

func (x *CompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compress_compress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressRequest.ProtoReflect.Descriptor instead.
func (*CompressRequest) Descriptor() ([]byte, []int) {
	return file_compress_compress_proto_rawDescGZIP(), []int{0}
}

func (x *CompressRequest) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type CompressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressResponse) Reset() {
	*x = CompressResponse{}
	mi := &file_compress_compress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressResponse) ProtoMessage() {}

func (x *CompressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compress_compress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressResponse.ProtoReflect.Descriptor instead.
func (*CompressResponse) Descriptor() ([]byte, []int) {
	return file_compress_compress_proto_rawDescGZIP(), []int{1}
}

func (x *CompressResponse) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

type DecompressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecompressRequest) Reset() {
	*x = DecompressRequest{}
	mi := &file_compress_compress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompressRequest) ProtoMessage() {}

func (x *DecompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compress_compress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompressRequest.ProtoReflect.Descriptor instead.
func (*DecompressRequest) Descriptor() ([]byte, []int) {
	return file_compress_compress_proto_rawDescGZIP(), []int{2}
}

func (x *DecompressRequest) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

type DecompressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecompressResponse) Reset() {
	*x = DecompressResponse{}
	mi := &file_compress_compress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecompressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecompressResponse) ProtoMessage() {}

func (x *DecompressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compress_compress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecompressResponse.ProtoReflect.Descriptor instead.
func (*DecompressResponse) Descriptor() ([]byte, []int) {
	return file_compress_compress_proto_rawDescGZIP(), []int{3}
}

func (x *DecompressResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_compress_compress_proto protoreflect.FileDescriptor

const file_compress_compress_proto_rawDesc = "" +
	"\n" +
	"\x17compress/compress.proto\x12\bcompress\"#\n" +
	"\x0fCompressRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\"&\n" +
	"\x10CompressResponse\x12\x12\n" +
	"\x04blob\x18\x01 \x01(\fR\x04blob\"'\n" +
	"\x11DecompressRequest\x12\x12\n" +
	"\x04blob\x18\x01 \x01(\fR\x04blob\"&\n" +
	"\x12DecompressResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw2\x98\x01\n" +
	"\n" +
	"Compressor\x12A\n" +
	"\bCompress\x12\x19.compress.CompressRequest\x1a\x1a.compress.CompressResponse\x12G\n" +
	"\n" +
	"Decompress\x12\x1b.compress.DecompressRequest\x1a\x1c.compress.DecompressResponseBDZBgithub.com/leonardopreuss/leet_date/internal/compresspb;compresspbb\x06proto3"

var (
	file_compress_compress_proto_rawDescOnce sync.Once
	file_compress_compress_proto_rawDescData []byte
)

func file_compress_compress_proto_rawDescGZIP() []byte {
	file_compress_compress_proto_rawDescOnce.Do(func() {
		file_compress_compress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compress_compress_proto_rawDesc), len(file_compress_compress_proto_rawDesc)))
	})
	return file_compress_compress_proto_rawDescData
}

var file_compress_compress_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_compress_compress_proto_goTypes = []any{
	(*CompressRequest)(nil),    // 0: compress.CompressRequest
	(*CompressResponse)(nil),   // 1: compress.CompressResponse
	(*DecompressRequest)(nil),  // 2: compress.DecompressRequest
	(*DecompressResponse)(nil), // 3: compress.DecompressResponse
}
var file_compress_compress_proto_depIdxs = []int32{
	0, // 0: compress.Compressor.Compress:input_type -> compress.CompressRequest
	2, // 1: compress.Compressor.Decompress:input_type -> compress.DecompressRequest
	1, // 2: compress.Compressor.Compress:output_type -> compress.CompressResponse
	3, // 3: compress.Compressor.Decompress:output_type -> compress.DecompressResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compress_compress_proto_init() }
func file_compress_compress_proto_init() {
	if File_compress_compress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compress_compress_proto_rawDesc), len(file_compress_compress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compress_compress_proto_goTypes,
		DependencyIndexes: file_compress_compress_proto_depIdxs,
		MessageInfos:      file_compress_compress_proto_msgTypes,
	}.Build()
	File_compress_compress_proto = out.File
	file_compress_compress_proto_goTypes = nil
	file_compress_compress_proto_depIdxs = nil
}
