// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: compress/compress.proto

package compresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Compressor_Compress_FullMethodName   = "/compress.Compressor/Compress"
	Compressor_Decompress_FullMethodName = "/compress.Compressor/Decompress"
)

// CompressorClient is the client API for Compressor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompressorClient interface {
	Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error)
	Decompress(ctx context.Context, in *DecompressRequest, opts ...grpc.CallOption) (*DecompressResponse, error)
}

type compressorClient struct {
	cc grpc.ClientConnInterface
}

func NewCompressorClient(cc grpc.ClientConnInterface) CompressorClient {
	return &compressorClient{cc}
}

func (c *compressorClient) Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompressResponse)
	err := c.cc.Invoke(ctx, Compressor_Compress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compressorClient) Decompress(ctx context.Context, in *DecompressRequest, opts ...grpc.CallOption) (*DecompressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecompressResponse)
	err := c.cc.Invoke(ctx, Compressor_Decompress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompressorServer is the server API for Compressor service.
// All implementations must embed UnimplementedCompressorServer
// for forward compatibility.
type CompressorServer interface {
	Compress(context.Context, *CompressRequest) (*CompressResponse, error)
	Decompress(context.Context, *DecompressRequest) (*DecompressResponse, error)
	mustEmbedUnimplementedCompressorServer()
}

// UnimplementedCompressorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompressorServer struct{}

func (UnimplementedCompressorServer) Compress(context.Context, *CompressRequest) (*CompressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compress not implemented")
}
func (UnimplementedCompressorServer) Decompress(context.Context, *DecompressRequest) (*DecompressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decompress not implemented")
}
func (UnimplementedCompressorServer) mustEmbedUnimplementedCompressorServer() {}
func (UnimplementedCompressorServer) testEmbeddedByValue()                    {}

// UnsafeCompressorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompressorServer will
// result in compilation errors.
type UnsafeCompressorServer interface {
	mustEmbedUnimplementedCompressorServer()
}

func RegisterCompressorServer(s grpc.ServiceRegistrar, srv CompressorServer) {
	// If the following call panics, it indicates UnimplementedCompressorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Compressor_ServiceDesc, srv)
}

func _Compressor_Compress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressorServer).Compress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Compressor_Compress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressorServer).Compress(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Compressor_Decompress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressorServer).Decompress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Compressor_Decompress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressorServer).Decompress(ctx, req.(*DecompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Compressor_ServiceDesc is the grpc.ServiceDesc for Compressor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compressor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compress.Compressor",
	HandlerType: (*CompressorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compress",
			Handler:    _Compressor_Compress_Handler,
		},
		{
			MethodName: "Decompress",
			Handler:    _Compressor_Decompress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compress/compress.proto",
}
